GET http://localhost:{{$dotenv API_PORT}}/people HTTP/1.1

###
POST http://localhost:{{$dotenv API_PORT}}/people HTTP/1.1
Content-Type: application/json

{
  "name":"Your name here"
}

###
PUT http://localhost:{{$dotenv API_PORT}}/people/1 HTTP/1.1
Content-Type: application/json

{
  "name":"Rowan who?"
}

###
DELETE http://localhost:{{$dotenv API_PORT}}/people/3 HTTP/1.1